### ISSUE TITLE
Can't resolve 'vue-md-player' in ...

### ISSUE THREAD

**Issue by Joy1024** [meyt/vue-md-player#1]
Hi, as I was using your player in my project I meet some problems I would like to ask you.
Use it as follows:
1. Add the npm `yarn add  vue-md-player`
2. Build my project use `yarn build`, but got the error as follows: 
![image](https://user-images.githubusercontent.com/3068746/81366053-5f2b3380-911c-11ea-9e87-e3b9f33b0a64.png)

3. I checked the file `package.json`.
   Find the line`"main": "dist/vue-md-player.esm.js"`, but can not find  the file in dist folder. 

Comparing the player with others I really like yours so I think you should have new update or current package, Thank you!!!

**Comment by meyt** [comment]
@Joy1024 Thank you, [v0.1.3](https://github.com/meyt/vue-md-player/releases/tag/v0.1.3) published.

**Comment by meyt** [comment]
828275b82478a68d33a7e960e7f8d87de25af207
