### ISSUE TITLE
Invalid documentation for Vue 2

### ISSUE THREAD

**Issue by Ju01110101** [meyt/vue-md-player#11]
Is there a simple way to make this plugin work with Nuxt by any chance?

**Comment by meyt** [comment]
@fabricepallaud, What you mean about Nuxt compatibility? this is just a Vue component, import and use.

**Comment by Ju01110101** [comment]
Using `Nuxt 2.14.7` and `Vue 2.6.12` and followed intructions from https://www.npmjs.com/package/@moddengine/vue-md-player exactly, I'm getting this error:

> "export 'VideoPlayer' was not found in 'vue-md-player'

**Comment by meyt** [comment]
@fabricepallaud That link is wrong. 
you are using `Vue 2`, follow instructions from this repository or https://www.npmjs.com/package/vue-md-player.

**Comment by Ju01110101** [comment]
@meyt oh sorry the link you just posted is actually the one I used. I did `npm install --save vue-md-player@1` and in `package.json` I see:

`"vue-md-player": "^1.0.4"`

The error occurs with that version.

**Comment by meyt** [comment]
Thank you @fabricepallaud. fixed.

**Comment by Ju01110101** [comment]
@meyt I think there's a little misunderstanding. To confirm, under `Nuxt 2.14` / `Vue 2` and after installing the package through `npm install --save vue-md-player@1`, the following fatal error still occurs: 

> "export 'VideoPlayer' was not found in 'vue-md-player'

**Comment by meyt** [comment]
@fabricepallaud I got what you said, only the the documentation was wrong. here is the working example https://github.com/meyt/vuemdplayer1-nuxt-example

**Comment by Ju01110101** [comment]
@meyt I'm sooo confused lol. In `nuxt.config.js` I see you have `components` property set to `true` so I just did that. Still getting `Can't resolve 'vue-md-player/dist/style.css'` and `[Vue warn]: Unknown custom element: <video-player> - did you register the component correctly?`

What change do I have to make in order for the issue to go away?

**Comment by meyt** [comment]
@fabricepallaud as i said, the documentation is updated. did you read [the link](https://github.com/meyt/vue-md-player/tree/v1#usage)?

**Comment by Ju01110101** [comment]
@meyt works now, thank you! :)
